services:
  webvirtcloud:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/webvirtcloud/data
    environment:
      - DJANGO_SECRET_KEY=dein-geheimes-passwort
