services:
  nonvc-desktop-server:
    build: .
    container_name: nonvc-desktop-server
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "25565:25565"
      - "22:22"
      - "8080:8080"
